version: '3'
services:
  postgres:
    image: "postgres:alpine"
    ports: 
     - "5432:5432"
    environment:
      POSTGRES_DB: "airline"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"       
      PGDATA : /var/lib/postgresql/data
    volumes:
        - ./data:/var/lib/postgresql/data
